-- ============================================================================
-- HQ dashboard performance — index the delivery-status lookup
-- Jul 2026. OPTIONAL but recommended. Safe: index only, no data/schema change.
-- Run on LOCAL first, then PROD (owner runs manually, as always).
-- ============================================================================
--
-- WHY
-- t_crm_order_status_history has indexes on order_id and changed_at, but NONE
-- on status_code. Every HQ query that resolves "when was this order delivered"
-- (revenue, growth, new customers, cohort, recency bands, missing invoices)
-- runs `WHERE status_code = 'delivered'`, which currently scans all ~45k rows.
--
-- MEASURED on the Jul-2026 prod replica: HQ Growth cold load 7.4s -> 4.8s (-35%).
-- Table is small (~45k rows) so the index builds in seconds and write overhead
-- on status changes is negligible.
--
-- The column order matters: status_code first (the equality filter), then
-- order_id (the GROUP BY / join key), then changed_at (the aggregated value) —
-- so the grouped "delivered date per order" subquery can be served from the
-- index alone.
--
-- SAFE TO RE-RUN? No — MySQL/MariaDB errors if the index already exists.
-- Check first:
--   SHOW INDEX FROM t_crm_order_status_history WHERE Key_name = 'idx_status_code_order';
-- If it returns a row, skip this script.
--
-- ROLLBACK:
--   DROP INDEX idx_status_code_order ON t_crm_order_status_history;
-- ============================================================================

CREATE INDEX idx_status_code_order
    ON t_crm_order_status_history (status_code, order_id, changed_at);
