-- =============================================================================
-- WhatsApp Auto-Reply (out-of-hours / day-off / custom rules) — Apr 2026
--
-- Run this in MySQL Workbench against production. Idempotent — safe to re-run.
--
-- This migration adds:
--   1. `t_wa_auto_replies` table — stores the actual rules (one row per rule).
--      Each row owns its trigger criteria (time window, day list, specific
--      dates, or "always") plus the message body and a per-rule cooldown.
--      Rules are evaluated in priority order; first match wins.
--
--   2. `auto_reply_rule_id` column on `t_wa_messages` — stamps which rule
--      generated an outbound auto-reply. Used both for display ("auto") and
--      for the cooldown lookup so we don't reply to the same customer over
--      and over for every inbound message they fire off back-to-back.
--
--   3. `wa_auto_reply_enabled` setting in `t_fin_config` (default '0') —
--      master kill-switch. Lets an operator turn the feature on/off
--      globally without deleting rules or running SQL.
--
--   4. Permission `manage_wa_auto_reply` — gates the settings UI (create,
--      edit, delete rules; toggle the master switch). Seeded for Admin,
--      Taimur, and Management roles.
--
-- Why an in-window text reply (not a Meta-approved template)?
-- The user's expectation is replies fire only when the customer has just
-- messaged us, which by definition opens the 24-hour customer-care window.
-- Inside that window WhatsApp Business API allows free-form session
-- messages, so we can ship the operator's own copy without going through
-- Meta template approval. If a rule somehow fires outside the 24h window
-- (clock skew, edge cases), the WhatsApp send will fail and we'll log the
-- error — no charge, no spam, no escalation.
-- =============================================================================

-- 1. Rules table.
CREATE TABLE IF NOT EXISTS `t_wa_auto_replies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL COMMENT 'Friendly label shown in the settings UI (e.g. "Out of working hours").',
  `message` TEXT NOT NULL COMMENT 'The reply body. Sent verbatim as a free-form WhatsApp text message inside the 24h window.',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Per-rule on/off. Master switch lives in t_fin_config.wa_auto_reply_enabled.',
  `priority` INT NOT NULL DEFAULT 100 COMMENT 'Lower number = evaluated first. First matching enabled rule wins; the rest are skipped for that inbound.',
  `match_mode` VARCHAR(20) NOT NULL DEFAULT 'time_window'
    COMMENT 'time_window | specific_dates | always. time_window uses days_of_week + start_time/end_time. specific_dates uses the JSON list. always matches every inbound (use as a low-priority fallback).',
  `days_of_week` VARCHAR(20) NULL DEFAULT NULL
    COMMENT 'Comma-separated 0..6 (0=Sunday, 6=Saturday). Empty/NULL on time_window means every day. Ignored for non-time_window modes.',
  `start_time` TIME NULL DEFAULT NULL COMMENT 'Inclusive lower bound for time_window. If end_time < start_time the window is treated as crossing midnight.',
  `end_time` TIME NULL DEFAULT NULL COMMENT 'Exclusive upper bound for time_window.',
  `specific_dates` TEXT NULL DEFAULT NULL
    COMMENT 'JSON array of YYYY-MM-DD strings (e.g. ["2026-12-25","2026-12-26"]). Used when match_mode=specific_dates.',
  `cooldown_hours` INT NOT NULL DEFAULT 6
    COMMENT 'Minimum hours between two auto-replies to the same conversation (across ALL rules). 0 disables cooldown.',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_enabled_priority` (`enabled`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp auto-reply rules (in-window text). See add_wa_auto_reply_apr2026.sql.';

-- 2. Stamp column on outbound messages.
-- NOTE: MySQL versions differ on `IF NOT EXISTS` for ADD COLUMN; this form
-- works on MySQL 8 and MariaDB 10.0+. If your version errors with
-- "Duplicate column", that's harmless — the column already exists.
ALTER TABLE `t_wa_messages`
ADD COLUMN IF NOT EXISTS `auto_reply_rule_id` BIGINT UNSIGNED NULL DEFAULT NULL
  COMMENT 'When set, this outbound row was generated by t_wa_auto_replies rule with this id. Used for cooldown lookup and "(auto)" badging in the chat UI.'
AFTER `template_name`;

ALTER TABLE `t_wa_messages`
ADD INDEX IF NOT EXISTS `idx_auto_reply_rule_id` (`auto_reply_rule_id`, `conversation_id`);

-- 3. Master kill-switch.
INSERT IGNORE INTO `t_fin_config`
    (`config_key`, `config_value`, `description`, `created_at`, `updated_at`)
VALUES
    ('wa_auto_reply_enabled',
     '0',
     'Master toggle for the WhatsApp auto-reply feature. 1 = active (rules in t_wa_auto_replies are evaluated on inbound messages); 0 = disabled (no auto-replies sent regardless of rule.enabled). Flip via the Auto-Reply settings modal.',
     NOW(), NOW());

-- 4. Permission.
INSERT INTO `t_sys_mobile_permission`
    (`permission_code`, `permission_name`, `permission_group`, `description`, `display_order`, `is_active`)
VALUES
    ('manage_wa_auto_reply', 'WhatsApp: Manage Auto-Reply Rules',
     'store_mode_orders',
     'Lets the user open the Auto-Reply settings modal, create/edit/delete rules, and toggle the master switch. Without this permission the gear button is hidden.',
     31, 1)
ON DUPLICATE KEY UPDATE
    permission_name = VALUES(permission_name),
    description     = VALUES(description),
    is_active       = VALUES(is_active);

-- 4a. Grant to Taimur + Management roles.
INSERT INTO `t_sys_role_mobile_permission` (role_id, mobile_permission_id)
SELECT r.id, p.id
FROM `t_sys_role` r
CROSS JOIN `t_sys_mobile_permission` p
WHERE (LOWER(r.urole_name) = 'taimur' OR LOWER(r.urole_name) LIKE '%management%')
  AND p.permission_code = 'manage_wa_auto_reply'
ON DUPLICATE KEY UPDATE role_id = role_id;

-- 4b. Admin (role_id = 1) safety net.
INSERT INTO `t_sys_role_mobile_permission` (role_id, mobile_permission_id)
SELECT 1, p.id
FROM `t_sys_mobile_permission` p
WHERE p.permission_code = 'manage_wa_auto_reply'
ON DUPLICATE KEY UPDATE role_id = role_id;

-- =============================================================================
-- Verification (run after the above to confirm everything is wired up):
--
--   SHOW CREATE TABLE t_wa_auto_replies;
--   SHOW COLUMNS FROM t_wa_messages LIKE 'auto_reply_rule_id';
--
--   SELECT config_key, config_value
--   FROM t_fin_config
--   WHERE config_key = 'wa_auto_reply_enabled';
--
--   SELECT r.urole_name, p.permission_code
--   FROM t_sys_role r
--   JOIN t_sys_role_mobile_permission rp ON rp.role_id = r.id
--   JOIN t_sys_mobile_permission     p  ON p.id = rp.mobile_permission_id
--   WHERE p.permission_code = 'manage_wa_auto_reply'
--   ORDER BY r.urole_name;
-- =============================================================================
